package OperacionesCajero;


/**
* OperacionesCajero/Operaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperacionesCajero.idl
* jueves 23 de mayo de 2013 07:39:52 AM CDT
*/

public interface Operaciones extends OperacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operaciones
