package OperacionesCajero;


/**
* OperacionesCajero/OperacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperacionesCajero.idl
* martes 21 de mayo de 2013 04:45:21 PM CDT
*/

public interface OperacionesOperations 
{
  boolean respuesta (String usuario, String contrasenia);
  String retirar (String id_usuario, int cantidad);
  void depositar (String id_usuario, int cantidad);
  int consultar (String id_usuario);
  void mensaje (String nombreUsuario);
} // interface OperacionesOperations
