package OperacionesCajero;


/**
* OperacionesCajero/OperacionesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperacionesCajero.idl
* domingo 19 de mayo de 2013 12:11:41 PM CDT
*/

abstract public class OperacionesHelper
{
  private static String  _id = "IDL:OperacionesCajero/Operaciones:1.0";

  public static void insert (org.omg.CORBA.Any a, OperacionesCajero.Operaciones that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OperacionesCajero.Operaciones extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OperacionesCajero.OperacionesHelper.id (), "Operaciones");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OperacionesCajero.Operaciones read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OperacionesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OperacionesCajero.Operaciones value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static OperacionesCajero.Operaciones narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OperacionesCajero.Operaciones)
      return (OperacionesCajero.Operaciones)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OperacionesCajero._OperacionesStub stub = new OperacionesCajero._OperacionesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static OperacionesCajero.Operaciones unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OperacionesCajero.Operaciones)
      return (OperacionesCajero.Operaciones)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OperacionesCajero._OperacionesStub stub = new OperacionesCajero._OperacionesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
