package OperacionesCajero;


/**
* OperacionesCajero/Operaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperacionesCajero.idl
* sábado 18 de mayo de 2013 02:48:16 PM CDT
*/

public interface Operaciones extends OperacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operaciones
