package OperacionesCajero;


/**
* OperacionesCajero/Operaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperacionesCajero.idl
* martes 21 de mayo de 2013 04:45:21 PM CDT
*/

public interface Operaciones extends OperacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operaciones
