package OperacionesCajero;


/**
* OperacionesCajero/OperacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperacionesCajero.idl
* sábado 18 de mayo de 2013 02:48:16 PM CDT
*/

public interface OperacionesOperations 
{
  boolean respuesta (String usuario, String contrasenia);
  void retirar (String id_usuario, int cantidad);
  void depositar (String id_usuario, int cantidad);
  int consultar (String id_usuario);
} // interface OperacionesOperations
