package OperacionesCajero;


/**
* OperacionesCajero/OperacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperacionesCajero.idl
* domingo 19 de mayo de 2013 12:11:41 PM CDT
*/

public interface OperacionesOperations 
{
  boolean respuesta (String usuario, String contrasenia);
  String retirar (String id_usuario, int cantidad);
  void depositar (String id_usuario, int cantidad);
  int consultar (String id_usuario);
} // interface OperacionesOperations
